language: python

python:  
  - "3.6"
install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt

# Service for postgre database
services:
  - postgresql 

env:
  global:
    - APP_SETTINGS=testing

# command to run tests
script:
  - py.test --cov-report term --cov=app
  - coverage report
before_script:
  - pip install -r requirements.txt
  - psql -c 'create database test_sendit;' -U postgres
 
 
after_success:
  - coveralls